{% set name = "autoafids" %}
{% set version = "1.1.0" %}
{% set ref = "51e7caafada94bea0fb4346e7437aecb3dd5e4aa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/afids/autoafids/archive/{{ ref }}.tar.gz
  sha256: 168ae1728af578ba2dc178f80402be6e6e4ad26959ebbce9f4d1f3cf57ceabf9

build:
  entry_points: 
    - autoafids = autoafids.run:app.run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0
    - snakebids >=0.14.0
    - appdirs >=1.4.4,<2.0.0
    - pulp <2.8.0  # [py<311]
    - pyvista >=0.44.2,<0.45.0

test:
  imports:
    - autoafids
  commands:
    - autoafids --help


about:
  home: https://github.com/khanlab/hippunfold
  summary: |
    End-to-end BIDS app for automated anatomical fiducial landmark regression.
  description: |
    AutoAFIDs is a BIDS-compliant application that automates the placement 
    and evaluation of anatomical fiducial landmarks (AFIDs).
  license: MIT
  license_file: LICENSE


extra:
  recipe-maintainers:
    - Dhananjhay