{% set name = "autoafids" %}
{% set version = "1.1.0" %}
{% set ref = "0495778fac62a789ba0970804fa007a73e18a6c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/afids/autoafids/archive/{{ ref }}.tar.gz
  sha256: 1c749b2c7d38f288e6590ee682998e8d27c99979e0b02ae5830f0bd5a11ad0a6

build:
  entry_points: 
    - autoafids = autoafids.run:app.run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.11
    - snakebids >=0.14.0,<0.15
    - appdirs >=1.4.4,<2.0.0
    - pyvista >=0.44.2,<0.45.0

test:
  imports:
      - autoafids
  commands:
    - autoafids --help


about:
  home: https://github.com/afids/autoafids
  summary: End-to-end BIDS app for automated anatomical fiducial landmark regression.
  description: AutoAFIDs is a BIDS-compliant application that automates the placement and evaluation of anatomical fiducial landmarks (AFIDs).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Dhananjhay