context:
  version: 1.1.0

package:
  name: autoafids
  version: ${{ version }}

source:
  git: https://github.com/afids/autoafids.git
  rev: 241e4b3ddecc82f1e245ad3c881b516a44ee33cd

build:
  script: ${{ PYTHON }} -m pip install
  python:
    entry_points: 
      - autoafids = autoafids.run:app.run
  noarch: python

requirements:
  host:
    - python >=3.11
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.11
    - snakebids >=0.14.0,<0.15
    - appdirs >=1.4.4,<2.0.0
    - pyvista >=0.44.2,<0.45.0

tests:
- python:
    imports:
      - autoafids
    pip_check: true
- script:
    - autoafids --help


about:
  summary: End-to-end BIDS app for automated anatomical fiducial landmark regression.
  description: AutoAFIDs is a BIDS-compliant application that automates the placement and evaluation of anatomical fiducial landmarks (AFIDs).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Dhananjhay