name: test workflow with wet run 
on:
  pull_request:

jobs:  
  wetrun_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Install non-python dependencies
        run: |
          sudo apt-get install -y graphviz-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: khanlab/actions/.github/actions/action-setup_task-installPyProject@v0.3.6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Python environments
        uses: khanlab/actions/.github/actions/action-setup_task-installPyProject@v0.3.6
        with:
          python-version: ${{ matrix.python-version }}
          install-library: true

      - name: Setup env for autoafids
        run: |
          echo "AUTOAFIDS_CACHE_DIR=`pwd`/test_data/autoafids_cache_dir" >> $GITHUB_ENV

      - name: Wetrun testing
        run: |
          set -eo pipefail
          poetry run autoafids test_data/bids_wetrun_testing test_out participant \
            --cores all --force-output --stereotaxy STN --fidqc --use-conda --conda-frontend conda | tee autoafids_output.log
        continue-on-error: false

      - name: Model accuracy check 
        run: |  
          set -eo pipefail
          poetry run python ./tests/test_fcsv_output.py \
            --autoafids_fcsv ./test_out/sub-001/afids-cnn/*.fcsv \
            --baseline_fcsv ./test_data/bids_wetrun_testing/sub-001/anat/sub-001*.fcsv | tee test_fcsv_output.log

